name: spajam2025_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flame: ^1.34.0
  flame_forge2d: ^0.19.2+2
  flutter_blue_plus: ^2.0.2
  flame_audio: ^2.11.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/audio/
